<a href="https://colab.research.google.com/github/wang201156/ycps0218/blob/main/EX03_02_%E5%85%AC%E5%8F%B8%E8%96%AA%E8%B3%87%E6%A6%82%E6%B3%81%E2%85%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import pandas as pd

data = {
    'ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Helen', 'Ivy', 'Jack'],
    'Age': [25, 30, 35, 40, 22, 29, 38, 27, 33, 31],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
    'Salary': [50000, 60000, 75000, 80000, 45000, 62000, 72000, 58000, 69000, 71000],
    'Department': ['IT', 'HR', 'Finance', 'Marketing', 'IT', 'HR', 'Finance', 'Marketing', 'IT', 'Finance']
}

df = pd.DataFrame(data)
df

    ID     Name  Age          City  Salary Department
0  101    Alice   25      New York   50000         IT
1  102      Bob   30   Los Angeles   60000         HR
2  103  Charlie   35       Chicago   75000    Finance
3  104    David   40       Houston   80000  Marketing
4  105      Eve   22       Phoenix   45000         IT
5  106    Frank   29  Philadelphia   62000         HR
6  107    Grace   38   San Antonio   72000    Finance
7  108    Helen   27     San Diego   58000  Marketing
8  109      Ivy   33        Dallas   69000         IT
9  110     Jack   31      San Jose   71000    Finance

In [39]:
avg_sal=df['Salary'].median()
df_hs=df
df_hs['High Salary'] = df_hs['Salary'].apply(lambda x: 'True' if x > df['Salary'].quantile(0.75) else 'False')
df_hs

    ID     Name  Age          City  Salary Department High Salary
0  101    Alice   25      New York   50000         IT       False
1  102      Bob   30   Los Angeles   60000         HR       False
2  103  Charlie   35       Chicago   75000    Finance        True
3  104    David   40       Houston   80000  Marketing        True
4  105      Eve   22       Phoenix   45000         IT       False
5  106    Frank   29  Philadelphia   62000         HR       False
6  107    Grace   38   San Antonio   72000    Finance        True
7  108    Helen   27     San Diego   58000  Marketing       False
8  109      Ivy   33        Dallas   69000         IT       False
9  110     Jack   31      San Jose   71000    Finance       False

In [40]:
df_hs_filtered = df_hs[df_hs['High Salary'] == 'False']
df_hs_filtered

    ID   Name  Age          City  Salary Department High Salary
0  101  Alice   25      New York   50000         IT       False
1  102    Bob   30   Los Angeles   60000         HR       False
4  105    Eve   22       Phoenix   45000         IT       False
5  106  Frank   29  Philadelphia   62000         HR       False
7  108  Helen   27     San Diego   58000  Marketing       False
8  109    Ivy   33        Dallas   69000         IT       False
9  110   Jack   31      San Jose   71000    Finance       False

In [44]:
new_data = [
    {'ID': 111, 'Name': 'Kevin', 'Age': 28, 'City': 'Austin', 'Salary': None, 'Department': 'IT'},
    {'ID': 112, 'Name': 'Lily', 'Age': 26, 'City': 'Seattle', 'Salary': 55000, 'Department': 'Marketing'},
    {'ID': 112, 'Name': 'Lily', 'Age': 26, 'City': 'Seattle', 'Salary': 55000, 'Department': 'Marketing'}
]
df = pd.concat([df, pd.DataFrame(new_data)], ignore_index=True)
df

     ID     Name  Age          City   Salary Department
0   101    Alice   25      New York  50000.0         IT
1   102      Bob   30   Los Angeles  60000.0         HR
2   103  Charlie   35       Chicago  75000.0    Finance
3   104    David   40       Houston  80000.0  Marketing
4   105      Eve   22       Phoenix  45000.0         IT
5   106    Frank   29  Philadelphia  62000.0         HR
6   107    Grace   38   San Antonio  72000.0    Finance
7   108    Helen   27     San Diego  58000.0  Marketing
8   109      Ivy   33        Dallas  69000.0         IT
9   110     Jack   31      San Jose  71000.0    Finance
10  111    Kevin   28        Austin      NaN         IT
11  112     Lily   26       Seattle  55000.0  Marketing
12  112     Lily   26       Seattle  55000.0  Marketing

找出空值的資料列，並填充空值（薪水依該部門平均值）

In [50]:
df_gp = df.groupby('Department')
df_gp['Salary'].mean()

Department
Finance      72666.666667
HR           61000.000000
IT           56666.666667
Marketing    62000.000000
Name: Salary, dtype: float64

In [51]:
#df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df['Salary'] = df_gp['Salary'].transform(lambda x: x.fillna(x.mean()))
df

     ID     Name  Age          City        Salary Department
0   101    Alice   25      New York  50000.000000         IT
1   102      Bob   30   Los Angeles  60000.000000         HR
2   103  Charlie   35       Chicago  75000.000000    Finance
3   104    David   40       Houston  80000.000000  Marketing
4   105      Eve   22       Phoenix  45000.000000         IT
5   106    Frank   29  Philadelphia  62000.000000         HR
6   107    Grace   38   San Antonio  72000.000000    Finance
7   108    Helen   27     San Diego  58000.000000  Marketing
8   109      Ivy   33        Dallas  69000.000000         IT
9   110     Jack   31      San Jose  71000.000000    Finance
10  111    Kevin   28        Austin  62666.666667         IT
11  112     Lily   26       Seattle  55000.000000  Marketing
12  112     Lily   26       Seattle  55000.000000  Marketing

刪除重複資料

In [46]:
df_cleaned = df.drop_duplicates(keep='last')
df_cleaned

     ID     Name  Age          City        Salary Department
0   101    Alice   25      New York  50000.000000         IT
1   102      Bob   30   Los Angeles  60000.000000         HR
2   103  Charlie   35       Chicago  75000.000000    Finance
3   104    David   40       Houston  80000.000000  Marketing
4   105      Eve   22       Phoenix  45000.000000         IT
5   106    Frank   29  Philadelphia  62000.000000         HR
6   107    Grace   38   San Antonio  72000.000000    Finance
7   108    Helen   27     San Diego  58000.000000  Marketing
8   109      Ivy   33        Dallas  69000.000000         IT
9   110     Jack   31      San Jose  71000.000000    Finance
10  111    Kevin   28        Austin  62666.666667         IT
12  112     Lily   26       Seattle  55000.000000  Marketing

新增欄位 'NewSalary'，如果薪水小於平均值則薪水加 500，否則維持原薪水；新增欄位 'RankSalary' 填入薪水排名。

In [48]:
df_cleaned['NewSalary'] =df_cleaned['Salary'].apply(lambda x: x+500 if x < df['Salary'].mean()  else x)
df_cleaned['RankSalary'] = df_cleaned['Salary'].rank(ascending=False, method='min')
df_cleaned['RankSalary'] = df_cleaned['RankSalary'].astype(int)
df_cleaned

<ipython-input-48-4c3691bf4a68>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['NewSalary'] =df_cleaned['Salary'].apply(lambda x: x+500 if x < df['Salary'].mean()  else x)
<ipython-input-48-4c3691bf4a68>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['RankSalary'] = df_cleaned['Salary'].rank(ascending=False, method='min')
<ipython-input-48-4c3691bf4a68>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['RankSalary'] = df_cleaned['RankSalary'].astype(int)

,ID,Name,Age,City,Salary,Department,NewSalary,RankSalary
0,101,Alice,25,New York,50000.000000,IT,50500.000000,11
1,102,Bob,30,Los Angeles,60000.000000,HR,60500.000000,8
2,103,Charlie,35,Chicago,75000.000000,Finance,75000.000000,2
3,104,David,40,Houston,80000.000000,Marketing,80000.000000,1
4,105,Eve,22,Phoenix,45000.000000,IT,45500.000000,12
5,106,Frank,29,Philadelphia,62000.000000,HR,62500.000000,7
6,107,Grace,38,San Antonio,72000.000000,Finance,72000.000000,3
7,108,Helen,27,San Diego,58000.000000,Marketing,58500.000000,9
8,109,Ivy,33,Dallas,69000.000000,IT,69000.000000,5
9,110,Jack,31,San Jose,71000.000000,Finance,71000.000000,4
10,111,Kevin,28,Austin,62666.666667,IT,62666.666667,6
12,112,Lily,26,Seattle,55000.000000,Marketing,55500.000000,10